/**
 * Target Central Resource Database API
 * REST API for data from Target Central Resource Database
 *
 * OpenAPI spec version: 20190612
 * Contact: oliverr@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

package tcrd.model

case class Filter(
  field: String,
  op: String,
  value: String)
