swagger: "2.0"
info:
  version: "20190612"
  title: Target Central Resource Database API
  description: REST API for data from Target Central Resource Database
  contact:
    name: Oliver Ruebenacker
    url: https://personal.broadinstitute.org/oliverr/
    email: oliverr@broadinstitute.org
paths:
  /status:
    get:
      summary: Status of the API
      operationId: getStatus
      responses:
        200:
          description: Success!
          schema:
            $ref: '#/definitions/Status'
  /possibleFilters:
    get:
      summary: Get list of fields and available filters
      operationId: getPossibleFilters
      responses:
        200:
          description: Success!
          schema:
            type: array
            items:
              $ref: '#/definitions/FilterOptions'
  /filterGenes:
    post:
      parameters:
        - 
          name: body
          in: body
          description: JSON object with list of genes and list of filters
          required: true
          schema: 
            $ref: '#/definitions/GenesFilterQuery'
      summary: Filter list of genes by one or more conditions
      operationId: filterGenes
      responses:
        200:
          description: Success!
          schema:
            type: array
            items: 
              type: string
definitions:
  Status:
    type: object
    required: ["id", "message"]
    additionalProperties: false
    properties: 
      id:
        type: string
        enum: ["initializing", "ready", "failed"]
      message:
        type: string
  FilterOptions:
    type: object
    required: ["field", "ops"]
    additionalProperties: false
    properties:
      field:
        type: string
      ops: 
        type: array
        items:
          type: string
  Filter:
    type: object
    required: ["field", "op", "value"]
    additionalProperties: false
    properties:
      field: 
        type: string
      op: 
        type: string
      value:
        type: string
  GenesFilterQuery:
    type: object
    required: ["genes", "filters"]
    additionalProperties: false
    properties:
      genes: 
        type: array
        items:
          type: string
      filters:
        type: array
        items:
          $ref: '#/definitions/Filter'

                    
                    
                
  
    
  