/**
 * Target Central Resource Database API
 * REST API for data from Target Central Resource Database
 *
 * OpenAPI spec version: 20190612
 * Contact: oliverr@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

import tcrd.server.api._
import io.swagger.app.{ ResourcesApp, SwaggerApp }
import javax.servlet.ServletContext
import org.scalatra.LifeCycle
import tcrd.db.api.mock.DbMockApi

class ScalatraBootstrap extends LifeCycle {
  implicit val swagger = new SwaggerApp

  override def init(context: ServletContext) {
    try {
      val dbApi = DbMockApi
      context mount (new DefaultApi(dbApi), "/Default/*")

      context mount (new ResourcesApp, "/api-docs/*")
    } catch {
      case e: Throwable => e.printStackTrace()
    }
  }
}
