/**
 * Target Central Resource Database API
 * REST API for data from Target Central Resource Database
 *
 * OpenAPI spec version: 20190612
 * Contact: oliverr@broadinstitute.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */

import io.swagger.app.{ ResourcesApp, SwaggerApp }
import javax.servlet.ServletContext
import org.scalatra.{ LifeCycle, ScalatraBase }
import tcrd.db.DbDefaultApi
import tcrd.db.config.DbConfig
import tcrd.server.api._

class ScalatraBootstrap extends LifeCycle {
  implicit val swagger = new SwaggerApp

  override def init(context: ServletContext) {
    try {
      val dbApi =
        DbDefaultApi(DbConfig.localFile) match {
          case Left(message) =>
            println(message)
            throw new RuntimeException(message)
          case Right(dbDefaultApi) => dbDefaultApi
        }

      context mount (new DefaultApi(dbApi), "/Default/*")

      context mount (new ResourcesApp, "/api-docs/*")
    } catch {
      case e: Throwable => e.printStackTrace()
    }
  }
}
